uploads: .kite9/uploads
sources:
- path: / 
  showDirectories: true
  pattern: "**/*.adl"
- path: / 
  showDirectories: true
  pattern: "**/*.svg"
templates: https://kite9.com/public/examples/basic.adl?format=adl
