uploads: .kite9/uploads
sources:
- path: / 
  showDirectories: true
  pattern: "**/*.adl"
- path: / 
  showDirectories: true
  pattern: "**/*.svg"
templatePath: /public/examples
templates: 
  - /public/examples/basic.adl
